"""Generate a PDF report summarizing findings."""
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import os
import logging

logger = logging.getLogger(__name__)

class ReportGenerator:
    """Create a PDF report with root causes and recommendations."""
    
    def generate(self, root_causes, recommendations, output_path):
        """Write the PDF file."""
        c = canvas.Canvas(output_path, pagesize=letter)
        width, height = letter
        
        # Title
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, height - 50, "Attack Path Analysis Report")
        
        # Root Causes
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, height - 100, "Root Causes:")
        c.setFont("Helvetica", 10)
        y = height - 120
        for cause in root_causes:
            c.drawString(70, y, f"- {cause.get('cause', 'Unknown')} (confidence: {cause.get('confidence', 0.0):.2f})")
            y -= 20
        
        # Recommendations
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y - 20, "Recommendations:")
        c.setFont("Helvetica", 10)
        y -= 40
        for rec in recommendations:
            c.drawString(70, y, f"- {rec}")
            y -= 20
        
        # Footer
        c.setFont("Helvetica-Oblique", 8)
        c.drawString(50, 30, "Generated by Cyber Attack Path Analyzer")
        
        c.save()
        logger.info(f"Report saved to {output_path}")